version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/simpleapp/docker-username"
    DOCKER_PASSWORD: "/simpleapp/docker-password"
    DOCKER_URL: "/simpleapp/docker-url"

phases:
  install:
    runtime-versions:
      python: 3.11
    
  
  pre_build:
    commands:
    - pip install -r requirements.txt

  build:
    commands:
    - echo "Building docker image"  
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"
    - docker build -t "$DOCKER_URL/$DOCKER_USERNAME/simple-flask-app.latest" .
    - docker push "$DOCKER_URL/$DOCKER_USERNAME/simple-flask-app.latest"
      
  post_build:
    commands:
      - echo "Build is successful"
